### ISSUE TITLE
multiple spaces in cell value converted to 1 space

### ISSUE THREAD

**Issue by Pachelbel1414** [martijn/xsv#13]
multiple spaces in cell value converted to 1 space
had cell value with "foo--bar" where each "-" was a space.
when read, xsv reported the cell value as "foo-bar", having only a single space.
windows, ruby 2.5.8p224, xsv (0.3.13)

**Comment by martijn** [comment]
Thanks for reporting. Could you verify that the current master resolves your issue?

**Comment by Pachelbel1414** [comment]
it fixes the issue.  thank you.

**Comment by martijn** [comment]
Great! Released 0.3.14 with the fix.
