### ISSUE TITLE
Xsv::Workbook.open does not accept Tempfile 

### ISSUE THREAD

**Issue by durcak** [martijn/xsv#14]
`Xsv::Workbook.open `does not accept Tempfile, so its not possible to parse ActiveStorage::Blob files, its return 

> NoMethodError: undefined method `start_with?' for #<Tempfile: (closed)>

**Comment by durcak** [comment]
Sorry, I find out that its possible to use simply `x = Xsv::Workbook.open(blob.download)`

**Comment by martijn** [comment]
Glad you got it working! Reopening because this is interesting and that NoMethodError is not helpful at all.

**Comment by martijn** [comment]
Fixed in 0.3.14
