### ISSUE TITLE
#<NoMethodError: undefined method `get_input_stream' for nil:NilClass>

### ISSUE THREAD

**Issue by durcak** [martijn/xsv#15]
Hi, I tried to parse this xlsx [file](https://www.filehosting.org/file/details/871204/import-run-correct.xlsx), but I am getting this error:

> x = Xsv::Workbook.open(file)     
                                                                                                        
> NoMethodError: undefined method `get_input_stream' for nil:NilClass
> from /Users/tomasdurcak/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/xsv-0.3.14/lib/xsv/workbook.rb:78:in `fetch_shared_strings'
> Caused by NoMethodError: undefined method `get_input_stream' for nil:NilClass
> from /Users/tomasdurcak/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/xsv-0.3.14/lib/xsv/workbook.rb:78:in `fetch_shared_strings'
> Caused by CSV::MalformedCSVError: Illegal quoting in line 2.
> from /Users/tomasdurcak/.rbenv/versions/2.6.6/lib/ruby/2.6.0/csv/parser.rb:879:in `parse_quotable_robust'

**Comment by martijn** [comment]
Thanks for reporting. Could you maybe upload the file somewhere that doesn't require me to register? Feel free to send it to the e-mail address in my profile.

**Comment by martijn** [comment]
Released 0.3.15 with a fix.
