### ISSUE TITLE
"Encountered unknown column type d"

### ISSUE THREAD

**Issue by fxckdead** [martijn/xsv#33]
I saw this issue #10 and i guess is the same error but for a different Column type. I have the stack from the sidekiq job:

```
2021-07-03T01:51:22.084Z 43432 TID-ovi6i5kkw WARN: Xsv::Error: Encountered unknown column type d
2021-07-03T01:51:22.084Z 43432 TID-ovi6i5kkw WARN: /Users/christian/.rvm/gems/ruby-2.6.1/gems/xsv-1.0.0/lib/xsv/sheet_rows_handler.rb:111:in `format_cell'
/Users/christian/.rvm/gems/ruby-2.6.1/gems/xsv-1.0.0/lib/xsv/sheet_rows_handler.rb:60:in `end_element'
/Users/christian/.rvm/gems/ruby-2.6.1/gems/xsv-1.0.0/lib/xsv/sax_parser.rb:68:in `block in parse'
/Users/christian/.rvm/gems/ruby-2.6.1/gems/xsv-1.0.0/lib/xsv/sax_parser.rb:19:in `loop'
/Users/christian/.rvm/gems/ruby-2.6.1/gems/xsv-1.0.0/lib/xsv/sax_parser.rb:19:in `parse'
/Users/christian/.rvm/gems/ruby-2.6.1/gems/xsv-1.0.0/lib/xsv/sheet.rb:64:in `each_row'
...
```

I put a log inside the `format_cell` method and i saw the problem was with the column of `type custom` with a date value `"2021-07-01T05:11:26.00000026635825825"`. 

I Attatch a sample excel file.

[github_sample.xlsx](https://github.com/martijn/xsv/files/6757745/github_sample.xlsx)

**Comment by martijn** [comment]
Thanks for reporting, this was fixed in version 1.0.4 that I just released.
