### ISSUE TITLE
Breakage on Excel files without cell column names

### ISSUE THREAD

**Issue by kjmph** [martijn/xsv#48]
Hi, I happened to hit upon an Excel file that has cells without a column name. Crazy, right? Anyway, a few quick fixes sorted that out. What do you think?

helpers.rb:
```ruby
    # Return the index number for the given Excel column name (i.e. "A1" => 0)
    def column_index(col)
      return if col == nil # <-- if receiving a nil column name, return
      col.each_codepoint.reduce(0) do |sum, n|
        break sum - 1 if n < A_CODEPOINT # reached a number

        sum * 26 + (n - A_CODEPOINT + 1)
      end
    end
```

sheet_bounds_handler.rb:
```ruby
    def start_element(name, attrs)
      case name
      #...
      when "v"
        col = column_index(@cell)
        @max_column = col if col != nil && col > @max_column # <-- Don't update @max_column
        @max_row = @row if @row > @max_row
      #...
```

sheet_rows_handler.rb:
```ruby
    def initialize(mode, empty_row, workbook, row_skip, last_row, &block)
      #...
      @current_cell = {}
      @current_cell_number = 0 # <-- Trackable cell number
      #...

    def start_element(name, attrs)
      case name
      when "c"
        @current_cell = attrs
        @current_cell_number += 1 # <-- Advance cell number
        @current_value.clear
      when "v", "is", "t"
        @store_characters = true
      when "row"
        @current_row = @empty_row.dup
        @current_cell_number = 0 # <-- Reset cell number
        @current_row_number = attrs[:r].to_i
      end
    end

    def end_element(name)
      case name
      #...
      when "c"
        col_index = column_index(@current_cell[:r])
        col_index = @current_cell_number unless col_index != nil # <-- use tracked cell number if there is no column name
      #...
```

Sorry for the quick code drop, don't have time for a pull request. Does this help?

**Comment by martijn** [comment]
Oh that is interesting. Do you know what application generated that file or can you maybe share an example?

**Comment by kjmph** [comment]
Unfortunately, I don't know the application that generated the file. Here are two sample files that cause the issue (and maybe highlight that I made a mistake in the cell number tracking??)

[example.xlsx](https://github.com/martijn/xsv/files/10361434/example.xlsx)
[example_no_column_names.xlsx](https://github.com/martijn/xsv/files/10361433/example_no_column_names.xlsx)

**Comment by kjmph** [comment]
Oh, haha, I bumped the cell number in start_element, it should be bumped in end_element. Sorry about that.

**Comment by martijn** [comment]
It’s probably not necessary to track the column number at all, instead we can just append the value to `@current_row` if `@column_index` fails or look up the header using an index on `@current_row.count`.

**Comment by kjmph** [comment]
Oh yes, another fine way to handle it. I was going for minimal changes to get it out and fixed in the moment. I'm already over the hurdle, so let me know what I can do to help. Either way, thanks for the project!

**Comment by martijn** [comment]
@kjmph Could you test if #50 solves the problem with your original file in both array and hash mode?

**Comment by kjmph** [comment]
I'm not sure when I'll have time to test.. maybe later this week? My apologies on my slow responses.

**Comment by martijn** [comment]
No problem, there’s no rush! Thanks for the update
